/**
 * database.js - Fachada de acceso a Datos y Persistencia
 * Re-exporta los submódulos especializados de /db para mantener 100% de compatibilidad hacia atrás.
 */

const { pool, DB_PATH, getSpainIsoTimestamp } = require('./db/connection');

const {
    SHIFT_CAPACITIES,
    SCHEDULE_BY_DAY,
    parseSpanishDate,
    checkAvailability,
    getAvailableTimeSlotsForDate,
    getUpcomingAvailableSlots,
    getNextAvailableDate,
    getFechasPreferencia
} = require('./db/availability');

const {
    createReservation,
    getReservation,
    getAllReservations,
    getReservationById,
    updateReservation,
    confirmReservation,
    cancelReservation,
    updateReservationStatus,
    autoUpdateReservationStatuses,
    findActiveReservation,
    findReservationForCancellation,
    findReservationByNameAndPhone,
    findActiveReservationsByName,
    findActiveReservationsByPhone,
    getMostRecentPendingReservationByPhone,
    normalizePhone,
    normalizeText,
    formatNationalityCode,
    formatLanguageCode,
    formatAllergiesInSpanish,
    formatDaysInSpanish
} = require('./db/reservations');

const {
    getGiftCard,
    updateGiftCardStatus,
    createGiftCard,
    getAllGiftCards,
    calculateSixMonthsValidity,
    isCardExpired,
    extractGiftCardCodeFromText
} = require('./db/giftCards');

const {
    getDynamicTexts,
    saveDynamicText,
    getMenuItems,
    saveMenuItems,
    getDisabledKeys,
    toggleDisabledKey,
    deleteCustomTextKey,
    getCustomRules,
    saveCustomRule,
    deleteCustomRule,
    getDraftChanges,
    addDraftChange,
    discardDraftChange,
    clearAllDraftChanges,
    publishAllDraftChanges,
    getLastPublishTimestamp,
    getAttachments,
    getAttachment,
    saveAttachment,
    deleteAttachment,
    getSystemSettings,
    updateSystemSetting
} = require('./db/dynamicContent');

const {
    addToWaitlist,
    getWaitlistPosition,
    getFirstWaitlistForSlot,
    removeFromWaitlist,
    getWaitlistEntry,
    cancelWaitlistEntry,
    findExistingWaitlistEntry
} = require('./db/waitlist');

const {
    getCategoryTagInfo,
    createSolicitud,
    getAllSolicitudes,
    getActiveHumanHandoverSolicitud,
    appendMessageToSolicitud,
    updateSolicitudStatus,
    deleteSolicitud,
    logUserChatHistory,
    getUserChatHistory,
    deleteUserChatHistory,
    archiveUserChatHistory,
    getAllWhatsAppConversations
} = require('./db/solicitudes');

const silencedNumbers = require('./db/silencedNumbers');

module.exports = {
    pool,
    DB_PATH,
    getSpainIsoTimestamp,
    SHIFT_CAPACITIES,
    SCHEDULE_BY_DAY,
    parseSpanishDate,
    checkAvailability,
    getAvailableTimeSlotsForDate,
    getUpcomingAvailableSlots,
    getNextAvailableDate,
    getFechasPreferencia,
    createReservation,
    getReservation,
    getAllReservations,
    getReservationById,
    updateReservation,
    confirmReservation,
    cancelReservation,
    updateReservationStatus,
    autoUpdateReservationStatuses,
    findActiveReservation,
    findReservationForCancellation,
    findReservationByNameAndPhone,
    findActiveReservationsByName,
    findActiveReservationsByPhone,
    getMostRecentPendingReservationByPhone,
    normalizePhone,
    normalizeText,
    formatNationalityCode,
    formatLanguageCode,
    formatAllergiesInSpanish,
    formatDaysInSpanish,
    getGiftCard,
    updateGiftCardStatus,
    createGiftCard,
    getAllGiftCards,
    calculateSixMonthsValidity,
    isCardExpired,
    extractGiftCardCodeFromText,
    getDynamicTexts,
    saveDynamicText,
    getMenuItems,
    saveMenuItems,
    getDisabledKeys,
    toggleDisabledKey,
    deleteCustomTextKey,
    getCustomRules,
    saveCustomRule,
    deleteCustomRule,
    getDraftChanges,
    addDraftChange,
    discardDraftChange,
    clearAllDraftChanges,
    publishAllDraftChanges,
    getLastPublishTimestamp,
    getAttachments,
    getAttachment,
    saveAttachment,
    deleteAttachment,
    getSystemSettings,
    updateSystemSetting,
    addToWaitlist,
    getWaitlistPosition,
    getFirstWaitlistForSlot,
    removeFromWaitlist,
    getWaitlistEntry,
    cancelWaitlistEntry,
    findExistingWaitlistEntry,
    getCategoryTagInfo,
    createSolicitud,
    getAllSolicitudes,
    getActiveHumanHandoverSolicitud,
    appendMessageToSolicitud,
    updateSolicitudStatus,
    deleteSolicitud,
    logUserChatHistory,
    getUserChatHistory,
    deleteUserChatHistory,
    archiveUserChatHistory,
    getAllWhatsAppConversations,
    getAllSilencedNumbers: silencedNumbers.getAllSilencedNumbers,
    isPhoneSilenced: silencedNumbers.isPhoneSilenced,
    addOrUpdateSilencedNumber: silencedNumbers.addOrUpdateSilencedNumber,
    deleteSilencedNumber: silencedNumbers.deleteSilencedNumber,
    toggleSilencedNumberActive: silencedNumbers.toggleSilencedNumberActive,
    bulkToggleSilencedNumbers: silencedNumbers.bulkToggleSilencedNumbers,
    bulkDeleteSilencedNumbers: silencedNumbers.bulkDeleteSilencedNumbers,
    bulkUpdateCategory: silencedNumbers.bulkUpdateCategory,
    seedSilencedNumbersFromTxt: silencedNumbers.seedSilencedNumbersFromTxt,
    inboxSettings: require('./db/inboxSettings'),
    getInboxSettings: require('./db/inboxSettings').getInboxSettings,
    saveInboxSettings: require('./db/inboxSettings').saveInboxSettings,
    setChatPin: require('./db/inboxSettings').setChatPin,
    setChatStatus: require('./db/inboxSettings').setChatStatus,
    setChatTags: require('./db/inboxSettings').setChatTags,
    setTagsOrder: require('./db/inboxSettings').setTagsOrder,
    saveCustomTag: require('./db/inboxSettings').saveCustomTag,
    deleteCustomTag: require('./db/inboxSettings').deleteCustomTag
};
