services:
  whatsapp-bot-admin:
    build:
      context: .
      dockerfile: Dockerfile
    image: casa-julian-whatsapp-bot:latest
    container_name: casa-julian-whatsapp-bot
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - /volume1/docker/casa-julian-whatsapp:/app
      - /app/node_modules
