services:
  - type: web
    name: casa-julian-whatsapp-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: WEBHOOK_VERIFY_TOKEN
        value: casajulian123
      - key: WHATSAPP_TOKEN
        value: EAAPS3Ie3sf4BSLp05hbL3dPrpu9ZAEif6bT9H2AOqnyCJMxgadw6Y8eu3ebbahSY4M2PoWyLHrWoopZCdKDIqtdFUISYzy7vzSnynPfRJbuo6qoZAvsCh6bVbVaMK0eltku8v1dZBShzTrI6sO9hDZCpzlKoNuUhmTzuwYIi0gXdhfxjfd85Fu82Nmtac3QZDZD
      - key: PHONE_NUMBER_ID
        value: 1232422906619224
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_DypfG4x1AEPH@ep-noisy-leaf-zayquj7g.c-2.eu-west-2.aws.neon.tech/neondb?sslmode=require
