-- ESQUEMA DE BASE DE DATOS PROFESIONAL POSTGRESQL PARA CASA JULIAN

CREATE TABLE IF NOT EXISTS clientes (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) UNIQUE NOT NULL,
    dni VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(100) NOT NULL,
    idioma VARCHAR(10) DEFAULT 'es',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reservas (
    id VARCHAR(30) PRIMARY KEY,
    cliente_dni VARCHAR(20) REFERENCES clientes(dni) ON DELETE CASCADE,
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    dni VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL,
    fecha VARCHAR(20) NOT NULL,
    hora VARCHAR(10) NOT NULL,
    comensales INT NOT NULL,
    estado VARCHAR(20) DEFAULT 'CONFIRMADA',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lista_espera (
    id VARCHAR(30) PRIMARY KEY,
    cliente_dni VARCHAR(20) REFERENCES clientes(dni) ON DELETE CASCADE,
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    dni VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL,
    fecha VARCHAR(20) NOT NULL,
    hora VARCHAR(10) NOT NULL,
    comensales INT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- ÍNDICES DE ALTO RENDIMIENTO PARA CONSULTAS RAPIDAS DE DISPONIBILIDAD Y BUSQUEDAS
CREATE INDEX IF NOT EXISTS idx_reservas_fecha_hora ON reservas(fecha, hora, estado);
CREATE INDEX IF NOT EXISTS idx_reservas_dni ON reservas(dni);
CREATE INDEX IF NOT EXISTS idx_lista_espera_fecha_hora ON lista_espera(fecha, hora);
